---
argument_specs:
  main:
    short_description: |-
      Install and configure the OpenStack Neutron networking component.
    description:
      - Creates databases and configures users
      - Creates OpenStack services and associated users
      - Creates OpenStack endpoints within OpenStack Keystone
      - Installs required operating system packages
      - Applies desired configuration using templates
      - Creates necessary network bridges
      - Configures OVN/Open-vSwitch
    options:
      openstack_neutron_db_name:
        type: str
        default: neutron
        description: Name of the MySQL database created.
      openstack_neutron_db_user:
        type: str
        default: neutron
        description: Database user created for the OpenStack Neutron component.
      openstack_neutron_db_password:
        type: str
        required: true
        description: Database password created for the O(openstack_neutron_db_user).
      openstack_neutron_service_user:
        type: str
        default: neutron
        description: User created in OpenStack Keystone for the Neutron component.
      openstack_neutron_service_password:
        type: str
        required: true
        description: Service password assigned to the O(openstack_neutron_service_user).
      openstack_neutron_metadata_secret:
        type: str
        required: true
        description: Secret shared between Nova and Neutron for communication.
      openstack_neutron_ovn_tunnel_address:
        type: str
        description: >-
          IP Address on the tunnel network for this node. Must be specified for
          all compute nodes.
      openstack_neutron_api_worker_count:
        type: int
        description: >-
          Number of API worker instances to start.  Defaults to the number of
          CPU cores present on the controller.
      openstack_neutron_designate_enabled:
        type: bool
        default: false
        description: >-
          Controls whether Neutron is integrated with Designate for automatic
          DNS record management.
      openstack_neutron_dns_domain:
        type: str
        default: openstacklocal
        description: >-
          Default DNS domain name to use for building hostnames on networks
          that do not have a domain name assigned.
      openstack_neutron_ptr_zone_email:
        type: str
        default: "admin@{{ openstack_neutron_dns_domain }}"
        description: The email address to be used when creating PTR zones.
      openstack_neutron_provider_networks:
        type: list
        elements: dict
        options:
          name:
            type: str
            required: true
            description: Name within OVN for the specified provider network.
          type:
            type: str
            required: true
            choices:
              - vlan
              - flat
            description: Type of underlying provider network being managed.
          range:
            type: str
            required: true
            description: Range of vlan ids (xxx:xxx) allowed on the provider network.
        description: >-
          List of provider networks to configure in Open-vSwitch/OVN.  Must be
          specified for the controller.
      openstack_neutron_provider_network_mappings:
        type: list
        elements: dict
        options:
          name:
            type: str
            required: true
            description: >-
              Name of the provider network.  Must match the value in
              O(openstack_neutron_provider_networks).
          bridge:
            type: str
            required: true
            description: Open-vSwitch bridge to be created for this provider network.
          interface:
            type: str
            required: true
            description: >-
              Physical network interface to be attached to the bridge for
              network communication.
        description: >-
          List of mappings from OVN networks to physical networks.  Required
          for compute nodes.
      openstack_neutron_tenant_network_types:
        type: list
        elements: str
        default:
          - geneve
        description: List of allowed tenant network types.
      openstack_neutron_geneve_network_ranges:
        type: list
        elements: str
        default:
          - 1:1000
        description: List of VLAN ranges allowed for geneve tenant networks.
      openstack_neutron_controller_packages:
        type: list
        elements: str
        default:
          - neutron-server
          - openvswitch-switch
          - ovn-central
        description: List of packages installed on the controller node for the Neutron component.
      openstack_neutron_compute_packages:
        type: list
        elements: str
        default:
          - neutron-common
          - neutron-plugin-ml2
          - neutron-ovn-metadata-agent
          - ovn-host
        description: List of packages installed on the compute nodes for the Neutron component.
      openstack_neutron_controller_services:
        type: list
        elements: str
        default:
          - neutron-server
        description: Services to be restarted during install (and/or configuration changes) on the controller node.
      openstack_neutron_compute_services:
        type: list
        elements: str
        default:
          - neutron-ovn-metadata-agent
        description: Services to be restarted during install (and/or configuration changes) on the compute nodes.
      openstack_neutron_service_description:
        type: str
        default: OpenStack Networking
        description: Human-readable description for the OpenStack Neutron service within Keystone.
