---
galaxy_info:
  role_name: openstack_designate
  author: dubzland
  description: Install and configure the OpenStack Designate DNSaaS component.
  license: MIT
  min_ansible_version: "2.13"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
  galaxy_tags:
    - devops
    - openstack
    - designate
    - dns
    - bind9
    - cloud
    - linux
    - ubuntu

dependencies: []
