---
namespace: dubzland
name: openstack
version: "1.2.0"
readme: README.md
authors:
  - Josh Williams <jdubz@dubzland.com>
description: Installs and configures the OpenStack cloud computing platform.
license:
  - MIT
tags:
  - linux
  - debian
  - ubuntu
  - openstack
  - devops

dependencies:
  ansible.posix: "*"
  community.general: "*"
  community.mysql: "*"
  openstack.cloud: "*"
  openvswitch.openvswitch: "*"

repository: https://git.dubzland.com/dubzland/ansible-collections/openstack

# The URL to any online docs
documentation: |
  https://docs.dubzland.io/ansible-collections/collections/dubzland/openstack/

# The URL to the homepage of the collection/project
homepage: https://git.dubzland.com/dubzland/ansible-collections/openstack

# The URL to the collection issue tracker
issues: https://git.dubzland.com/dubzland/ansible-collections/openstack/-/issues
build_ignore:
  - .ansible-lint
  - .cache
  - .gitignore
  - .gitlab-ci.yml
  - .venv
  - .yamllint
  - requirements-*.txt
  - extensions
