---
- name: Restart OpenStack Magnum services
  ansible.builtin.service:
    name: "{{ openstack_magnum_services }}"
    state: restarted

- name: Restart Apache2
  ansible.builtin.service:
    name: apache2
    state: restarted
