---
galaxy_info:
  role_name: openstack_ceph_client
  author: dubzland
  description: Configuration related tasks for OpenStack components requiring Ceph access
  license: MIT
  min_ansible_version: "2.13"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
  galaxy_tags:
    - devops
    - openstack
    - cinder
    - storage
    - ceph
    - nova
    - cloud
    - linux
    - ubuntu

dependencies: []
