---
- name: Retrieve the OpenStack cluster facts
  dubzland.openstack.openstack_get_fact:
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    as: "{{ item.as }}"
  loop:
    - section: controller
      option: address
      as: _controller_address
    - section: controller
      option: http_host
      as: _controller_http_host
    - section: mysql
      option: address
      as: _mysql_address
    - section: cloud
      option: region
      as: _openstack_region_name
    - section: cloud
      option: domain
      as: _openstack_domain_name
    - section: cloud
      option: name
      as: _openstack_cloud_name

- name: Provision the OpenStack Placement component
  ansible.builtin.import_role:
    name: dubzland.openstack.openstack_component
  vars:
    openstack_component_database_user: "{{ openstack_placement_db_user }}"
    openstack_component_database_password: "{{ openstack_placement_db_password }}"
    openstack_component_databases:
      - "{{ openstack_placement_db_name }}"
    openstack_component_user: "{{ openstack_placement_service_user }}"
    openstack_component_password: "{{ openstack_placement_service_password }}"
    openstack_component_services:
      - name: placement
        type: placement
        description: "{{ openstack_placement_service_description }}"
        endpoints:
          - interface: public
            url: "{{ _controller_http_host }}:8778"
          - interface: internal
            url: "{{ _controller_http_host }}:8778"
          - interface: admin
            url: "{{ _controller_http_host }}:8778"

- name: Ensure the required Placement service packages are installed
  ansible.builtin.package:
    name: "{{ openstack_placement_packages }}"
    state: present

- name: Ensure the OpenStack Placement configuration is present
  dubzland.openstack.openstack_config_template:
    src: etc/placement/placement.conf.j2
    dest: /etc/placement/placement.conf
    owner: root
    group: placement
    mode: "0640"
  notify: Restart OpenStack Placement services

- name: Perform an OpenStack Placement DB sync
  ansible.builtin.command:
    cmd: placement-manage db sync
  changed_when: false
  become: true
  become_user: placement
