---
galaxy_info:
  role_name: openstack_component
  author: dubzland
  description: Manages OpenStack component services, databases, and endpoints
  license: MIT
  min_ansible_version: "2.13"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
  galaxy_tags:
    - devops
    - openstack
    - cloud
    - linux
    - ubuntu

dependencies: []
