---
- name: Ensure required NFS packages are installed
  ansible.builtin.package:
    name: "{{ openstack_cinder_storage_nfs_packages }}"
    state: present
  notify: Restart OpenStack Cinder services
  when: "('storage' in group_names) and openstack_cinder_ceph_client"

- name: Ensure cinder NFS shares are configured
  ansible.builtin.template:
    src: etc/cinder/nfs_shares.j2
    dest: /etc/cinder/nfs_shares
    owner: root
    group: cinder
    mode: "0640"
  notify: Restart OpenStack Cinder services
  when: "('storage' in group_names) and openstack_cinder_nfs_shares is defined"
