---
openstack_designate_packages:
  - bind9utils
  - bind9-doc
  - designate
  - python3-designate-dashboard
  - designate-mdns
  - designate-producer
  - designate-worker
openstack_designate_services:
  - designate-central
  - designate-api
  - designate-worker
  - designate-producer
  - designate-mdns
openstack_designate_service_description: OpenStack DNS
