---
- name: Populate the Neutron database
  ansible.builtin.command:
    cmd: >-
      neutron-db-manage --config-file /etc/neutron/neutron.conf
      --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head
  changed_when: false
  become: true
  become_user: neutron
  when:
    - ansible_local['openstack']['neutron']['need_db_upgrade'] | bool

- name: Disable the db upgrade fact
  dubzland.openstack.openstack_set_fact:
    section: neutron
    option: need_db_upgrade
    value: "False"

- name: Refresh local facts
  ansible.builtin.setup:
    filter: ansible_local
    gather_subset: "!all"
