---
- name: Ensure Open-vSwitch is configured to listen on localhost
  ansible.builtin.lineinfile:
    path: /etc/default/openvswitch-switch
    regexp: '^#?\s*OVS_CTL_OPTS'
    line: 'OVS_CTL_OPTS="--ovsdb-server-options=''--remote=ptcp:6640:127.0.0.1''"'
  notify: Restart Open-vSwitch

- name: Perform controller specific tasks
  ansible.builtin.include_tasks: ovn-setup-controller.yml
  when: "'controller' in group_names"

- name: Perform compute specific tasks
  ansible.builtin.include_tasks: ovn-setup-compute.yml
  when: "'compute' in group_names"
