---
- name: Ensure Open-vSwitch is configured to listen on localhost
  ansible.builtin.lineinfile:
    path: /etc/default/openvswitch-switch
    regexp: '^#?\s*OVS_CTL_OPTS'
    line: 'OVS_CTL_OPTS="--ovsdb-server-options=''--remote=ptcp:6640:127.0.0.1''"'
  notify: Restart Open-vSwitch

- name: Ensure the ovs-record-hostname service is disabled
  # see: https://bugs.launchpad.net/cloud-archive/+bug/2017757
  ansible.builtin.systemd:
    name: ovs-record-hostname
    enabled: false
    state: stopped
  when: "'compute' in group_names"

- name: Ensure the ovn-northd service is started and enabled
  ansible.builtin.systemd:
    name: ovn-northd
    state: started
    enabled: true
  when: "'controller' in group_names"

- name: Ensure connection settings are configured for ovn northbound/southbound
  ansible.builtin.command:
    cmd: "{{ item }}"
  loop:
    - ovn-nbctl set-connection ptcp:6641:0.0.0.0 -- set connection . inactivity_probe=60000
    - ovn-sbctl set-connection ptcp:6642:0.0.0.0 -- set connection . inactivity_probe=60000
  changed_when: false
  when: "'controller' in group_names"
  register: _ovn_connection_settings
  until: _ovn_connection_settings is success
  retries: 5
  delay: 2

- name: Ensure the ovn-controller service is started and enabled
  ansible.builtin.systemd:
    name: ovn-controller
    state: started
    enabled: true
  when: "'compute' in group_names"

- name: Ensure the openvswitch hostname is set
  ansible.builtin.command:
    cmd: "ovs-vsctl set open_vswitch . external-ids:hostname='{{ ansible_facts['nodename'] }}'"
  changed_when: false
  when: "'compute' in group_names"

- name: Ensure CMS Options for Gateway Scheduling are set
  ansible.builtin.command:
    cmd: "ovs-vsctl set open . external-ids:ovn-cms-options=enable-chassis-as-gw"
  changed_when: false
  when: "'compute' in group_names"

- name: Ensure the OVN southbound connection is configured
  ansible.builtin.command:
    cmd: "ovs-vsctl set open . external-ids:ovn-remote=tcp:{{ _controller_address }}:6642"
  changed_when: false
  when: "'compute' in group_names"

- name: Ensure supported OVN overlay protocols are configured
  ansible.builtin.command:
    cmd: ovs-vsctl set open . external-ids:ovn-encap-type=geneve
  changed_when: false
  when: "'compute' in group_names"

- name: Ensure the OVN tunnel address is configured
  ansible.builtin.command:
    cmd: >-
      ovs-vsctl set open .
      external-ids:ovn-encap-ip={{
        openstack_neutron_ovn_tunnel_address | ansible.utils.ipaddr('address')
      }}
  changed_when: false
  when: "'compute' in group_names"

- name: Retrieve the existing OVSDB manager(s)
  ansible.builtin.command:
    cmd: ovs-vsctl get-manager
  changed_when: false
  register: existing_ovsdb_managers
  when: "'compute' in group_names"

- name: Ensure the proper OVSDB manager is configured
  ansible.builtin.command:
    cmd: >-
      ovs-vsctl --id @manager
      create Manager "target=\"ptcp:6640:127.0.0.1\""
      -- add Open_vSwitch . manager_options @manager
  changed_when: false
  when:
    - "'compute' in group_names"
    - "'ptcp:6640:127.0.0.1' not in existing_ovsdb_managers.stdout_lines"

- name: Ensure provider network bridges are present
  openvswitch.openvswitch.openvswitch_bridge:
    bridge: "{{ item }}"
    fail_mode: standalone
    state: present
  loop: "{{ openstack_neutron_provider_networks | map(attribute='bridge') }}"
  when: "'compute' in group_names"

- name: Ensure ports are attached to provider network bridges
  openvswitch.openvswitch.openvswitch_port:
    bridge: "{{ item.bridge }}"
    port: "{{ item.interface }}"
    state: present
  loop: "{{ openstack_neutron_provider_networks }}"
  when: "'compute' in group_names"

- name: Set the provider network mappings
  ansible.builtin.set_fact:
    _provider_network_mappings: >-
      {{
        _provider_network_mappings
        | default([])
        | union(['%s:%s' | format(item.name, item.bridge)])
      }}
  loop: "{{ openstack_neutron_provider_networks }}"
  when: "'compute' in group_names"

- name: Ensure the OVN bridge mappings are configured
  ansible.builtin.command:
    cmd: >-
      ovs-vsctl set open .
      external-ids:ovn-bridge-mappings={{ _provider_network_mappings | join(',') }}
  when: "'compute' in group_names"
  changed_when: false
